In [18]:
print("We are learning the numpy library of python.")

We are learning the numpy library of python.


In [19]:
import numpy as np
# create an array
arr=np.array([11,23,45,2,2,444,22])
print(arr)

[ 11  23  45   2   2 444  22]


In [20]:
# perform the mathematical operations
print(arr + 10)
print(arr *2)
print(arr - 1)
print(arr/2)
print(arr)

[ 21  33  55  12  12 454  32]
[ 22  46  90   4   4 888  44]
[ 10  22  44   1   1 443  21]
[  5.5  11.5  22.5   1.    1.  222.   11. ]
[ 11  23  45   2   2 444  22]


In [21]:
#Create a 2D array
arr1=np.array([[1,2],[3,4]])
print(arr1 * 3)

[[ 3  6]
 [ 9 12]]


In [22]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
ones = np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
arange = np.arange(0,10,3)
print(arange)

[0 3 6 9]


In [25]:
linspace=np.linspace(0,1,5)
print(linspace)

[0.   0.25 0.5  0.75 1.  ]


In [35]:
arr = np.array([[2,3,4],[6,7,8]])
print(arr.size)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

6
(2, 3)
2
int64


In [39]:
arr1=np.array([4,6,8])
arr2=np.array([1,3,5])
print(arr1)
print(arr2)
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[4 6 8]
[1 3 5]
[ 5  9 13]
[3 3 3]
[ 4 18 40]
[4.  2.  1.6]


In [42]:
arr = np.array([[1,2],[4,5]])
print(arr.sum())
print(arr.mean())

12
3.0


In [44]:
arr = np.array([1,3,2,4,5,56,67,7])
print(arr[1:4])

[3 2 4]


In [46]:
a = np.array([1,2,3])
b = np.array([[1],[2],[3]])
print(a+b)


[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [50]:
a1 = np.array([1,2,3,4,5,6,7,8])
reshaped = a1.reshape(2,4)
print(reshaped)
print(a1)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [53]:
arr = np.array([[1,2],[3,4]])
print(arr)
print(arr.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [70]:
rand = np.random.rand(3,2)
print(rand)

[[4.18138193e-01 7.42242475e-01]
 [9.80279899e-01 1.04639988e-01]
 [7.32681509e-04 6.25945255e-01]]


In [83]:
integers = np.random.randint(1,10,(2,2))
print(integers)

[[3 6]
 [6 8]]
